config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  scope "/:locale" do
    
    
    get '/', to: 'welcome#index', as: 'welcome'
    get '/dashboard', to: 'welcome#dashboard', as: 'dashboard'
    
    resources :web_apps, path: 'webapps'

  end

  scope '/api' do
    scope '/v1' do
      
    end
  end
  root :to => "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/web_app.rb
class WebApp < ApplicationRecord
  belongs_to :user
  has_many :web_app_key, :dependent => :delete_all
  validates :page, uniqueness: true
  
  def test_api_key
    web_app_key = WebAppKey.where(:test => true, :web_app_id => self.id).first
    web_app_key.api_key
  end

  def api_key
    web_app_key = WebAppKey.where(:test => false, :web_app_id => self.id).first
    web_app_key.api_key
  end

  def create_keys
    WebAppKey.create(
      :test => true,
      :web_app => self)
    WebAppKey.create(
      :test => false,
      :web_app => self)
  end

  private
end

app/controllers/web_apps_controller.rb
class WebAppsController < ApplicationController
  before_action :set_web_app, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /web_apps
  # GET /web_apps.json
  def index
    @web_apps = WebApp.where(:user => current_user)
  end

  # GET /web_apps/1
  # GET /web_apps/1.json
  def show
  end

  # GET /web_apps/new
  def new
    @web_app = WebApp.new
  end

  # GET /web_apps/1/edit
  def edit
  end

  # POST /web_apps
  # POST /web_apps.json
  def create
    @web_app = WebApp.new(web_app_params)
    @web_app.user = current_user
    respond_to do |format|
      WebApp.transaction do 
        if @web_app.save
          @web_app.create_keys
          format.html { redirect_to @web_app, notice: 'Web app was successfully created.' }
          format.json { render :show, status: :created, location: @web_app }
        else
          format.html { render :new }
          format.json { render json: @web_app.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /web_apps/1
  # PATCH/PUT /web_apps/1.json
  def update
    respond_to do |format|
      if @web_app.update(web_app_params)
        format.html { redirect_to @web_app, notice: 'Web app was successfully updated.' }
        format.json { render :show, status: :ok, location: @web_app }
      else
        format.html { render :edit }
        format.json { render json: @web_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_apps/1
  # DELETE /web_apps/1.json
  def destroy
    @web_app.destroy
    respond_to do |format|
      format.html { redirect_to web_apps_url, notice: 'Web app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_web_app
      @web_app = WebApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def web_app_params
      params.fetch(:web_app, {}).permit(:page, :description)
    end
end

app/helpers/web_app_helper.rb
module WebAppHelper
end

app/helpers/web_apps_helper.rb
module WebAppsHelper
  def api_key(web_app, blank_message="&nbsp;")
    web_app_key = WebAppKey.where(:test => false, :web_app_id => web_app.id).first
    web_app_key.api_key
  end
  def test_api_key(web_app, blank_message="&nbsp;")
    web_app_key = WebAppKey.where(:test => true, :web_app_id => web_app.id).first
    web_app_key.api_key
  end
end

app/views/web_apps/_form.html.erb
<%= form_for(web_app) do |f| %>
  <% if web_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web_app.errors.count, "error") %> prohibited this web_app from being saved:</h2>

      <ul>
      <% web_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label(:page, t("controller.webapp.page")) %><br />
    <%= f.text_field :page, autofocus: true, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label(:description, t("controller.webapp.description") ) %><br />
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit t("buttons.save"), class: "btn btn-success" %>
  </div>
<% end %>

app/views/web_apps/edit.html.erb
<h1>Editing Web App</h1>

<%= render 'form', web_app: @web_app %>

<%= link_to 'Show', @web_app %> |
<%= link_to 'Back', web_apps_path %>

app/views/web_apps/index.html.erb
<% content_for :body_title do %>
  <%= raw t("controller."+controller_name) %>
<% end %>

<div class="row">
  <% @web_apps.each do |web_app| %>
    <div class="col-xs-12 col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <i class="fa fa-certificate"></i>
          <%= web_app.page %>
        </div>
        <div class="panel-body">
          <%= web_app.description %><br>
          <b>Test Api Key:</b> 
          <%= text_field_tag :test_api_key, web_app.test_api_key, class: "form-control"%>
          <br>
          <b>Api Key:</b>
          <div class="input-group">
            <%= password_field_tag :api_key, web_app.api_key, class: "form-control"%>
            <div class="input-group-addon" id="show-api-key" style="cursor: pointer;">
              <i class="fa fa-eye" ></i>
            </div>
          </div>
          <br>
        </div>
        <div class="panel-footer">
          <%#= link_to 'Show', web_app %>
          <% @web_app = web_app %>
          <%= render "layouts/destroy_modal", collection: @web_app %>
          <%= link_to t('buttons.edit'), edit_web_app_path(web_app), class: "btn btn-primary" %>
          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#destroy_<%=@web_app.id%>">
            <%= t("buttons.destroy") %>
          </button>
          
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Web App', new_web_app_path, class: "btn btn-success" %>
<br>
<br>
<br>

<% content_for :extra_js do %>
  <%= javascript_include_tag "controllers/web_app/web_app_index" %>
<% end %>

app/views/web_apps/new.html.erb
<% content_for :body_title do %>
  <%= raw t("controller.new_webapp") %>
<% end %>


<%= render 'form', web_app: @web_app %>

<%= link_to 'Back', web_apps_path %>

app/views/web_apps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_web_app_path(@web_app) %> |
<%= link_to 'Back', web_apps_path %>